version: '2'

networks:
  freelancer:

services:
  ca.cert.freelancerDomain.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.cert.freelancerDomain.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.cert.freelancerDomain.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/24540b5a964a1a05791ff312d68cbd0b7f409ef748295414fdce59fd0aa38a5e_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/cert.freelancerDomain.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.cert.freelancerDomain.com
    networks:
      - freelancer
   