version: '2'

networks:
  freelancer:

services:
  orderer1.freelancerDomain.com:
    container_name: orderer1.freelancerDomain.com
    image: hyperledger/fabric-orderer:1.4.7
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererOrg
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./config/:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/freelancerDomain.com/orderers/orderer1.freelancerDomain.com/:/etc/hyperledger/msp/orderer
    depends_on:
      - kafka1.freelancerDomain.com
      - kafka2.freelancerDomain.com
      - kafka3.freelancerDomain.com
      - kafka4.freelancerDomain.com  
    networks:
      - freelancer

  orderer2.freelancerDomain.com:
    container_name: orderer2.freelancerDomain.com
    image: hyperledger/fabric-orderer:1.4.7
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererOrg
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 8050:7050
    volumes:
        - ./config/:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/freelancerDomain.com/orderers/orderer2.freelancerDomain.com/:/etc/hyperledger/msp/orderer
    depends_on:
      - kafka1.freelancerDomain.com
      - kafka2.freelancerDomain.com
      - kafka3.freelancerDomain.com
      - kafka4.freelancerDomain.com  
    networks:
      - freelancer

  kafka1.freelancerDomain.com:
    container_name: kafka1.freelancerDomain.com
    extends:
      file: ./base/kafka-base.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=1
    ports:
      - 9092:9092
      - 9093:9093
    depends_on:
      - zookeeper1.freelancerDomain.com
      - zookeeper2.freelancerDomain.com
      - zookeeper3.freelancerDomain.com
    networks:
      - freelancer

  kafka2.freelancerDomain.com:
    container_name: kafka2.freelancerDomain.com
    extends:
      file: ./base/kafka-base.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=2
    ports:
      - 10092:9092
      - 10093:9093
    depends_on:
      - zookeeper1.freelancerDomain.com
      - zookeeper2.freelancerDomain.com
      - zookeeper3.freelancerDomain.com
    networks:
      - freelancer
  kafka3.freelancerDomain.com:
    container_name: kafka3.freelancerDomain.com
    extends:
      file: ./base/kafka-base.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=3
    ports:
      - 11092:9092
      - 11093:9093
    depends_on:
      - zookeeper1.freelancerDomain.com
      - zookeeper2.freelancerDomain.com
      - zookeeper3.freelancerDomain.com
    networks:
      - freelancer

  kafka4.freelancerDomain.com:
    container_name: kafka4.freelancerDomain.com
    extends:
      file: ./base/kafka-base.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=4
    ports:
      - 12092:9092
      - 12093:9093
    depends_on:
      - zookeeper1.freelancerDomain.com
      - zookeeper2.freelancerDomain.com
      - zookeeper3.freelancerDomain.com
    networks:
      - freelancer
  zookeeper1.freelancerDomain.com:
    container_name: zookeeper1.freelancerDomain.com
    extends:
      file: ./base/kafka-base.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=1
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    networks:
      - freelancer

  zookeeper2.freelancerDomain.com:
    container_name: zookeeper2.freelancerDomain.com
    extends:
      file: ./base/kafka-base.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=2
    ports:
      - 12181:2181
      - 12888:2888
      - 13888:3888
    networks:
      - freelancer

  zookeeper3.freelancerDomain.com:
    container_name: zookeeper3.freelancerDomain.com
    extends:
      file: ./base/kafka-base.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=3
    ports:
      - 22181:2181
      - 22888:2888
      - 25888:3888
    networks:
      - freelancer

  peer0.prog.freelancerDomain.com:
    container_name: peer0.prog.freelancerDomain.com
    image: hyperledger/fabric-peer:1.4.7
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.prog.freelancerDomain.com
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=ProgOrg
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer0.prog.freelancerDomain.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.prog.freelancerDomain.com:7051
      - CORE_PEER_GOSSIP_ENDPOINT=peer0.prog.freelancerDomain.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.prog.freelancerDomain.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=net_freelancer
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/prog.freelancerDomain.com/peers/peer0.prog.freelancerDomain.com/msp:/etc/hyperledger/msp/peer
        - ./crypto-config/peerOrganizations/prog.freelancerDomain.com/users:/etc/hyperledger/msp/users
        - ./config:/etc/hyperledger/configtx
    depends_on:
      - orderer1.freelancerDomain.com
      - orderer2.freelancerDomain.com
      - couchdb1
    networks:
      - freelancer

  couchdb1:
    container_name: couchdb1
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 5984:5984
    networks:
      - freelancer

  peer1.prog.freelancerDomain.com:
    container_name: peer1.prog.freelancerDomain.com
    image: hyperledger/fabric-peer:1.4.7
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.prog.freelancerDomain.com
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=ProgOrg
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer1.prog.freelancerDomain.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=net_freelancer
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 8051:7051
      - 8053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/prog.freelancerDomain.com/peers/peer1.prog.freelancerDomain.com/msp:/etc/hyperledger/msp/peer
        - ./crypto-config/peerOrganizations/prog.freelancerDomain.com/users:/etc/hyperledger/msp/users
        - ./config:/etc/hyperledger/configtx
    depends_on:
      - orderer1.freelancerDomain.com
      - orderer2.freelancerDomain.com
      - couchdb2
    networks:
      - freelancer

  couchdb2:
    container_name: couchdb2
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 6984:5984
    networks:
      - freelancer

  peer0.cert.freelancerDomain.com:
    container_name: peer0.cert.freelancerDomain.com
    image: hyperledger/fabric-peer:1.4.7
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.cert.freelancerDomain.com
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=CertOrg
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer0.cert.freelancerDomain.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=net_freelancer
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb3:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 9051:7051
      - 9053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/cert.freelancerDomain.com/peers/peer0.cert.freelancerDomain.com/msp:/etc/hyperledger/msp/peer
        - ./crypto-config/peerOrganizations/cert.freelancerDomain.com/users:/etc/hyperledger/msp/users
        - ./config:/etc/hyperledger/configtx
    depends_on:
      - orderer1.freelancerDomain.com
      - orderer2.freelancerDomain.com
      - couchdb3
    networks:
      - freelancer

  couchdb3:
    container_name: couchdb3
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 7984:5984
    networks:
      - freelancer

  peer1.cert.freelancerDomain.com:
    container_name: peer1.cert.freelancerDomain.com
    image: hyperledger/fabric-peer:1.4.7
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.cert.freelancerDomain.com
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=CertOrg
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer1.cert.freelancerDomain.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=net_freelancer
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb4:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 10051:7051
      - 10053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/cert.freelancerDomain.com/peers/peer1.cert.freelancerDomain.com/msp:/etc/hyperledger/msp/peer
        - ./crypto-config/peerOrganizations/cert.freelancerDomain.com/users:/etc/hyperledger/msp/users
        - ./config:/etc/hyperledger/configtx
    depends_on:
      - orderer1.freelancerDomain.com
      - orderer2.freelancerDomain.com
      - couchdb4
    networks:
      - freelancer

  couchdb4:
    container_name: couchdb4
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 8984:5984
    networks:
      - freelancer

  peer0.design.freelancerDomain.com:
    container_name: peer0.design.freelancerDomain.com
    image: hyperledger/fabric-peer:1.4.7
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.design.freelancerDomain.com
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=DesignOrg
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer0.design.freelancerDomain.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.design.freelancerDomain.com:7051
      - CORE_PEER_GOSSIP_ENDPOINT=peer0.design.freelancerDomain.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.design.freelancerDomain.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=net_freelancer
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb5:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 11051:7051
      - 11053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/design.freelancerDomain.com/peers/peer0.design.freelancerDomain.com/msp:/etc/hyperledger/msp/peer
        - ./crypto-config/peerOrganizations/design.freelancerDomain.com/users:/etc/hyperledger/msp/users
        - ./config:/etc/hyperledger/configtx
    depends_on:
      - orderer1.freelancerDomain.com
      - orderer2.freelancerDomain.com
      - couchdb5
    networks:
      - freelancer

  couchdb5:
    container_name: couchdb5
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 9984:5984
    networks:
      - freelancer
  
  peer1.design.freelancerDomain.com:
    container_name: peer1.design.freelancerDomain.com
    image: hyperledger/fabric-peer:1.4.7
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.design.freelancerDomain.com
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=DesignOrg
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer1.design.freelancerDomain.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=net_freelancer
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb6:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 12051:7051
      - 12053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/design.freelancerDomain.com/peers/peer1.design.freelancerDomain.com/msp:/etc/hyperledger/msp/peer
        - ./crypto-config/peerOrganizations/design.freelancerDomain.com/users:/etc/hyperledger/msp/users
        - ./config:/etc/hyperledger/configtx
    depends_on:
      - orderer1.freelancerDomain.com
      - orderer2.freelancerDomain.com
      - couchdb6
    networks:
      - freelancer

  couchdb6:
    container_name: couchdb6
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 10984:5984
    networks:
      - freelancer

  cli1:
    container_name: cli1
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.prog.freelancerDomain.com:7051
      - CORE_PEER_LOCALMSPID=ProgOrg
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/prog.freelancerDomain.com/users/Admin@prog.freelancerDomain.com/msp
      - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/go/:/opt/gopath/src/chaincode/go/
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./config:/etc/hyperledger/configtx
        - $GOPATH/src/github.com/hyperledger/fabric/:/opt/gopath/src/github.com/hyperledger/fabric/
    networks:
      - freelancer
  cli2:
    container_name: cli2
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.design.freelancerDomain.com:7051
      - CORE_PEER_LOCALMSPID=DesignOrg
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/design.freelancerDomain.com/users/Admin@design.freelancerDomain.com/msp
      - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/chaincode/
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./config:/etc/hyperledger/configtx
        - $GOPATH/src/github.com/hyperledger/fabric/:/opt/gopath/src/github.com/hyperledger/fabric/
    networks:
      - freelancer